const cars = [
	{
		model: "civic",
		brand: "honda",
		img: "/images/cars.png",
		pickupDate: "",
		returnDate: "",
		year: "2021",
		pricePerDay: "15",
		Passengers: "5",
		Gearshift: "automatic",
		Type: "sedan",
		id: "c17f",
	},
	{
		model: "corolla",
		brand: "toyota",
		img: "/images/electric.png",
		pickupDate: "",
		returnDate: "",
		year: 2022,
		pricePerDay: "10",
		Gearshift: "automatic",
		Passengers: "5",
		Type: "sedan",
		id: "afa0",
	},
	{
		model: "phantom",
		brand: "rolls royce",
		img: "/images/luxury.png",
		pickupDate: "",
		returnDate: "",
		year: 2022,
		pricePerDay: "40",
		Gearshift: "manual",
		Passengers: "4",
		Type: "convertible",
		id: "445f",
	},
	{
		model: "camry",
		brand: "toyota",
		img: "/images/car1.png",
		pickupDate: "",
		returnDate: "",
		year: 2022,
		pricePerDay: "15",
		Gearshift: "manual",
		Passengers: "5",
		Type: "sedan",
		id: "a865",
	},
	{
		model: "rav4",
		brand: "toyota",
		img: "/images/car2.png",
		pickupDate: "",
		returnDate: "",
		year: 2023,
		pricePerDay: "15",
		Gearshift: "automatic",
		Passengers: "7",
		Type: "SUV",
		id: "cb64",
	},
	{
		model: "blazer",
		brand: "chevrolet",
		img: "/images/car3.png",
		pickupDate: "",
		returnDate: "",
		year: 2023,
		pricePerDay: "22",
		Gearshift: "manual",
		Passengers: "5",
		Type: "SUV",
		id: "7db1",
	},
	{
		model: "X1",
		brand: "bmw",
		img: "/images/car4.png",
		pickupDate: "",
		returnDate: "Mon, 15 Apr 2024",
		year: 2021,
		pricePerDay: "27",
		Gearshift: "automatic",
		Passengers: "5",
		Type: "SUV",
		id: "449f",
	},
	{
		model: "iX",
		brand: "bmw",
		img: "/images/car5.png",
		pickupDate: "",
		returnDate: "",
		year: 2021,
		pricePerDay: "30",
		Gearshift: "manual",
		Passengers: "7",
		Type: "SUV",
		id: "4a3e",
	},
	{
		model: "z4",
		brand: "bmw",
		img: "/images/car6.png",
		pickupDate: "",
		returnDate: "Mon, 15 Apr 2024",
		year: 2020,
		pricePerDay: "28",
		Gearshift: "automatic",
		Passengers: "4",
		Type: "convertible",
		id: "b45b",
	},
	{
		model: "mustang",
		brand: "ford",
		img: "/images/car7.png",
		pickupDate: "",
		returnDate: "",
		year: 2022,
		pricePerDay: "18",
		Gearshift: "manual",
		Passengers: "4",
		Type: "convertible",
		id: "3d01",
	},
	{
		model: "bentayga",
		brand: "bentley",
		img: "/images/car8.png",
		pickupDate: "",
		returnDate: "",
		year: 2023,
		pricePerDay: "32",
		Gearshift: "automatic",
		Passengers: "7",
		Type: "SUV",
		id: "1151",
	},
	{
		model: "continental",
		brand: "bentley",
		img: "/images/car9.png",
		pickupDate: "",
		returnDate: "Mon, 15 Apr 2024",
		year: 2022,
		pricePerDay: "24",
		Gearshift: "manual",
		Passengers: "7",
		Type: "convertible",
		id: "28d4",
	},
	{
		model: "2 series",
		brand: "bmw",
		img: "/images/car10.png",
		pickupDate: "",
		returnDate: "",
		year: 2023,
		pricePerDay: "25",
		Gearshift: "automatic",
		Passengers: "5",
		Type: "sedan",
		id: "de89",
	},
	{
		model: "sentra",
		brand: "nissan",
		img: "/images/car11.png",
		pickupDate: "",
		returnDate: "Sat, 30 Mar 2024",
		year: 2023,
		pricePerDay: "20",
		Gearshift: "manual",
		Passengers: "5",
		Type: "sedan",
		id: "8554",
	},
	{
		model: "camry",
		brand: "toyota",
		img: "/images/car12.png",
		pickupDate: "",
		returnDate: "Mon, 15 Apr 2024",
		year: 2024,
		pricePerDay: "26",
		Gearshift: "automatic",
		Passengers: "5",
		Type: "sedan",
		id: "3ba4",
	},
	{
		model: "8 series",
		brand: "bmw",
		img: "/images/car13.png",
		pickupDate: "",
		returnDate: "",
		year: 2024,
		pricePerDay: "35",
		Gearshift: "manual",
		Passengers: "4",
		Type: "convertible",
		id: "6216",
	},
	{
		model: "suburban",
		brand: "chevrolet",
		img: "/images/car14.png",
		pickupDate: "",
		returnDate: "",
		year: 2022,
		pricePerDay: "32",
		Gearshift: "automatic",
		Passengers: "7",
		Type: "SUV",
		id: "67b5",
	},
	{
		model: "tahoe",
		brand: "chevrolet",
		img: "/images/car15.png",
		pickupDate: "",
		returnDate: "",
		year: 2023,
		pricePerDay: "30",
		Gearshift: "automatic",
		Passengers: "7",
		Type: "SUV",
		id: "92eb",
	},
	{
		model: "escalade",
		brand: "cadillac",
		img: "/images/car16.png",
		pickupDate: "",
		returnDate: "",
		year: 2023,
		pricePerDay: "29",
		Gearshift: "automatic",
		Passengers: "7",
		Type: "SUV",
		id: "8e23",
	},
	{
		model: "cayanne",
		brand: "porsche",
		img: "/images/suv.png",
		pickupDate: "",
		returnDate: "Sat, 30 Mar 2024",
		year: 2023,
		pricePerDay: "25",
		Gearshift: "manual",
		Passengers: "7",
		Type: "SUV",
		id: "67fa",
	},
];

export default cars;
