const unregisteredUsers = [
	{
		id: 1,
		firstName: "cristiano",
		lastName: "ronaldo",
		email: "cris@email",
		phone: "0987",
		bookings: [
			{
				country: "venezuela",
				carImg: "/images/car2.png",
				carBrand: "toyota",
				carModel: "rav4",
				pickupLocation: "Miami Int Airport",
				returnLocation: "Caracas Int Airport",
				pickupDate: "Sat, 30 Mar 2024",
				returnDate: "Wed, 17 Apr 2024",
				pickupTime: "8:28 AM",
				returnTime: "1:28 PM",
				rentalDays: 18,
				pricePerDay: "15",
				totalPrice: 270,
				totalPlusAddons: 413.64,
				addons: [
					{
						_id: "65d24cec323ccd0a6b05b50b",
						name: "Toddler seat",
						price: "2.99",
						details: "A seat for children from 1 to 4 years old",
						img: "/images/babyseat.png",
					},
					{
						_id: "65d24cec323ccd0a6b05b50c",
						name: "Gps",
						price: "4.99",
						details: "stay connected and never get lost",
						img: "/images/gps.png",
					},
				],
			},
		],
	},
	{
		id: "2",
		firstName: "luka",
		lastName: "modric",
		email: "luka@email",
		phone: "567",
		bookings: [
			{
				country: "venezuela",
				carImg: "/images/car4.png",
				carBrand: "bmw",
				carModel: "X1",
				pickupLocation: "Caracas Int Airport",
				returnLocation: "Caracas Int Airport",
				pickupDate: "Thu, 25 Apr 2024",
				returnDate: "Tue, 30 Apr 2024",
				pickupTime: "4:55 AM",
				returnTime: "12:55 PM",
				rentalDays: 5,
				pricePerDay: "27",
				totalPrice: 135,
				totalPlusAddons: 159.95,
				addons: [
					{
						id: "3",
						name: "Gps",
						price: "4.99",
						details: "stay connected and never get lost",
						img: "/images/gps.png",
					},
				],
			},
		],
	},
	{
		id: "3",
		firstName: "phil",
		lastName: "foden",
		email: "phil@email",
		phone: "567",
		bookings: [],
	},
	{
		id: "4",
		firstName: "kevin",
		lastName: "de bruyne",
		email: "kevin@email",
		phone: "159",
		bookings: [],
	},
	{
		id: "5",
		firstName: "mariquin",
		lastName: "cat",
		email: "mariquin@email",
		phone: "567",
		bookings: [],
	},
];

export default unregisteredUsers;
